ARG baseimage

FROM $baseimage

ARG navdvdurl="test"
ARG vsixurl=""
ARG isbcsandbox="N"

ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS NAVDVDURL=$navdvdurl VSIXURL=$vsixurl IsBcSandbox=$isbcsandbox

COPY ./buildimage.ps1 /Run/buildimage.ps1

RUN \Run\buildimage.ps1
