ARG baseimage
ARG navdvdurl
ARG vsixurl
ARG isbcsandbox="N"

FROM $baseimage

ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=$isbcsandbox

COPY ./buildimage.ps1 C:/RUN/buildimage.ps1

RUN echo "-NAVDVDURL $navdvdurl -VSIXURL $vsixurl"

RUN .\Run\buildimage.ps1 -NAVDVDURL $NAVDVDURL -VSIXURL $VSIXURL
