ARG baseimage
ARG navdvdurl=""
ARG vsixurl=""
ARG isbcsandbox="N"

FROM $baseimage

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=$isbcsandbox

COPY ./buildimage.ps1 /buildimage.ps1

RUN .\buildimage.ps1 -NAVDVDURL "$($env:navdvdurl)" -VSIXURL "$($env:vsixurl)"
