ARG baseimage

FROM $baseimage

ARG navdvdurl=""
ARG vsixurl=""
ARG legal=""
ARG created=""
ARG country=""
ARG version=""
ARG platform=""

ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS NAVDVDURL=$navdvdurl VSIXURL=$vsixurl IsBcSandbox=Y

COPY ./buildimage.ps1 /Run/buildimage.ps1

RUN \Run\buildimage.ps1

ENV DatabaseServer="" DatabaseInstance="" DatabaseName=""

LABEL legal="$legal" \
      created="$created" \
      nav="" \
      cu="" \
      country="$country" \
      version="$version" \
      platform="$platform"
