ARG baseimage

FROM $baseimage

ARG created \
    tag \
    osversion \
    filesonly \
    only24

ENV only24=$only24 \
    filesonly=$filesonly

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

COPY Run /Run/

RUN . C:\Run\SetupGeneric.ps1

RUN Write-Host 'Installing SqlServer Module in PowerShell 7'; \
    pwsh -Command 'Install-Module -Name SqlServer -RequiredVersion 22.2.0 -Scope AllUsers -Force'; \
    Write-Host 'Done'

HEALTHCHECK --interval=30s --timeout=10s CMD [ "powershell", ".\\Run\\HealthCheck.ps1" ]

EXPOSE 1433 80 8080 443 7045-7049 7083

CMD .\Run\start.ps1

LABEL maintainer="Dynamics SMB" \
      eula="https://go.microsoft.com/fwlink/?linkid=861843" \
      tag="$tag" \
      created="$created" \
      osversion="$osversion" \
      filesonly="yes"
